<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<div class="pi-body">
    <div class="container">
        <div class="row">
            <div class="pi-body-title">
                <?php if ($module == 'system') { ?>
                    <h1>
                        <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                            <?php echo _escape($sitename); ?>
                        </a>
                    </h1>
                <?php } else { ?>
                    <h2>
                        <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                            <?php echo _escape($sitename); ?>
                        </a>
                    </h2>
                <?php } ?>
            </div>
            <!-- Header: brand, slogan, user bar -->
            <header class="pi-header">
                <nav class="navbar navbar-default clearfix">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav pi-navbar-nav">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>"><span class="pi-navbar-nav-icon"><i class="fa fa-home"></i></span><span class="pi-navbar-nav-text">خانه</span></a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/pad" title="دفترچه یادداشت"><span class="pi-navbar-nav-icon"><i class="fa fa-book"></i></span><span class="pi-navbar-nav-text">دفترچه یادداشت</span></a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/kiosk" title="کیوسک"><span class="pi-navbar-nav-icon"><i class="fa fa-newspaper-o"></i></span><span class="pi-navbar-nav-text">کیوسک</span></a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/together" title="با همدیگر"><span class="pi-navbar-nav-icon"><i class="fa fa-users"></i></span><span class="pi-navbar-nav-text">با همدیگر</span></a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/alarm-art" title="زنگ هنر"><span class="pi-navbar-nav-icon"><i class="fa fa-paint-brush"></i></span><span class="pi-navbar-nav-text">زنگ هنر</span></a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/working-time" title="وقت کار"><span class="pi-navbar-nav-icon"><i class="fa fa-briefcase"></i></span><span class="pi-navbar-nav-text">وقت کار</span></a></li>
                        </ul>
                        <div class="navbar-form navbar-right col-md-4">
                            <?php echo $this->widget('search-search'); ?>
                        </div>
                    </div>
                </nav>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-header-block clearfix pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </header>
            <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
            <section class="pi-section">
                <div class="pi-section-center clearfix">
                    <?php $piMainContaineClass = 'col-md-12'; ?>
                    <?php if (isset($blocks['1']) || isset($blocks['8'])) { ?>
                    <div class="pi-side-container col-md-3">
                        <!-- Left zone -->
                        <?php if (!empty($blocks['1'])) { ?>
                            <div class="pi-zone-1">
                                <?php foreach ($blocks['1'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <!-- Right zone -->
                        <?php if (isset($blocks['8'])) { ?>
                            <div class="pi-zone-8">
                                <?php foreach ($blocks['8'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php $piMainContaineClass = 'col-md-9'; ?>
                    </div>
                    <?php } ?>
                    <div class="pi-main-container <?php echo $piMainContaineClass; ?>">
                        <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
                        <!-- Flash messenger -->
                        <?php include $this->template('flash-messenger'); ?>
                        <div class="clearfix">
                            <!-- Center top zone -->
                            <?php if (isset($blocks['2'])) { ?>
                                <div class="pi-zone-2">
                                    <?php foreach ($blocks['2'] as $block) {
                                        include $blockTemplate;
                                    } ?>
                                </div>
                            <?php } ?>
                            <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                                <div class="row">
                                    <div class="col-md-6 pi-zone-3">
                                        <?php
                                        if (isset($blocks['3'])) {
                                            foreach ($blocks['3'] as $block) {
                                                include $blockTemplate;
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class="col-md-6 pi-zone-4">
                                        <?php
                                        if (isset($blocks['4'])) {
                                            foreach ($blocks['4'] as $block) {
                                                include $blockTemplate;
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                            <?php } ?>
                            <!-- Module content starts -->
                            <?php if (!empty($content)) { ?>
                                <div class="<?php echo $module; ?>">
                                    <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                        <?php echo $content; ?>
                                    </div>
                                    <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                                </div>
                            <?php } ?>
                            <!-- Module content ends -->
                            <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                                <div class="row">
                                    <div class="col-md-6 pi-zone-5">
                                        <?php
                                        if (isset($blocks['5'])) {
                                            foreach ($blocks['5'] as $block) {
                                                include $blockTemplate;
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class="col-md-6 pi-zone-6">
                                        <?php
                                        if (isset($blocks['6'])) {
                                            foreach ($blocks['6'] as $block) {
                                                include $blockTemplate;
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                            <?php } ?>
                            <!-- Center bottom zone -->
                            <?php if (isset($blocks['7'])) { ?>
                                <div class="pi-zone-7">
                                    <?php foreach ($blocks['7'] as $block) {
                                        include $blockTemplate;
                                    } ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-section-bottom clearfix pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </section>
            <!-- Footer: sitelink -->
            <footer class="pi-footer clearfix">
                <div class="pi-footer-body clearfix">
                    <div class="col-md-3">
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>news/pad" title="دفترچه یادداشت">دفترچه یادداشت</a></h4>
                        <ul class="list-unstyled">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/knowledge" title="دانش">دانش</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/social" title="اجتماعی">اجتماعی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/popularization-of-science" title="ترویج علم">ترویج علم</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/dreams" title="خیالی ها">خیالی ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/literary-forum" title="ادبی ها">ادبی ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/trip" title="سفر">سفر</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/food" title="خوراکی">خوراکی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/life-style" title="سبک زندگی">سبک زندگی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/sporadic" title="پراکنده">پراکنده</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>news/kiosk" title="کیوسک">کیوسک</a></h4>
                        <ul class="list-unstyled pi-footer-list">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/nojum" title="نجوم">نجوم</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/daneshmand" title="دانشمند">دانشمند</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/danestaniha" title="دانستنیها">دانستنیها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/jamejam" title="جام جم">جام جم</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/other-magazines" title="سایر مجله ها">سایر مجله ها</a></li>
                        </ul>
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>news/together" title="با همدیگر">با همدیگر</a></h4>
                        <ul class="list-unstyled">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/lectures" title="سخنرانی ها">سخنرانی ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/events" title="رویدادها">رویدادها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/generated-content" title="تولید محتوا">تولید محتوا</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>news/alarm-art" title="زنگ هنر">زنگ هنر</a></h4>
                        <ul class="list-unstyled pi-footer-list">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/projects" title="پروژه ها">پروژه ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/paintings" title="نقاشی ها">نقاشی ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/memory-album" title="آلبوم خاطرات">آلبوم خاطرات</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/other-art-alarm" title="سایر">سایر</a></li>
                        </ul>
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>news/working-time" title="وقت کار">وقت کار</a></h4>
                        <ul class="list-unstyled">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/consultation" title="مشاوره">مشاوره</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/design" title="طراحی ها">طراحی ها</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>news/teaching" title="تدریس">تدریس</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4><a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a></h4>
                        <ul class="list-unstyled pi-footer-list">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/about-me" title="درباره من">درباره من</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>contact" title="تماس با من">تماس با من</a></li>
                        </ul>
                        <div class="pi-social">
                            <h4>شبکه های اجتماعی</h4>
                            <ul class="list-inline">
                                <li id="pi-social-twitter"><a title="تویتر" href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li id="pi-social-facebook"><a title="فیسبوک" href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li id="pi-social-pinterest"><a title="پین‌ترست" href="#" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                                <li id="pi-social-google"><a title="گوگل پلاس" href="#" target="_blank" rel="Publisher"><i class="fa fa-google-plus"></i></a></li>
                                <li id="pi-social-instagram"><a title="اینستاگرام" href="#" target="_blank"><i class="fa fa-instagram"></i></a></li>
                                <li id="pi-social-foursquare"><a title="Foursquare" href="#" target="_blank"><i class="fa fa-foursquare"></i></a></li>
                                <li id="pi-social-linkedin"><a title="linkedin" href="#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="pi-footer-copyright">
                    <div class="row">
                        <div class="text-left col-md-6" data-rel="license">تمام حقوق مطالب برای <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                        <div class="text-right col-md-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>
</body>
</html>